<Project Sdk="Dalamud.NET.Sdk/15.0.0">
    <PropertyGroup>
        <PackageProjectUrl>https://github.com/ShiftyKiwi/CurrencyAlert.git</PackageProjectUrl>
        <Version>2.2.2.18</Version>
        <AssemblyName>KiwiCurrencyAlert</AssemblyName>
        <TargetFramework>net10.0-windows</TargetFramework>
        <DalamudApiLevel>15</DalamudApiLevel>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\KamiLib\KamiLib.csproj" />
        <ProjectReference Include="..\KamiToolKit\KamiToolKit.csproj" />
    </ItemGroup>
</Project>


